### ISSUE TITLE
Configuration of port other than 8080 possible?

### ISSUE THREAD

**Issue by FrankBergemann** [cescoffier/quarkus-todo-app#22]
Hi,
Can Quarkus todo be configured to be launched on a another port, ie not on port 8080?
This would really be helpful.
Kind regards
-- Frank

**Comment by cescoffier** [comment]
You can add in the `application.properties` the following property:

```
quarkus.http.port=9000
```

You can also pass this property as system variable or env property (QUARKUS_HTTP_PORT)

**Comment by FrankBergemann** [comment]
Hi Clement,
I added
`quarkus.http.port=8087 `
to the application.properties. However, it doesn't seem to work properly. Here is part of the console output upon app startup:

```
Hibernate: 
    
    alter table Todo 
       add constraint UK_oxfuur9jdyqshux5rm7g7ga6c unique (title)
Hibernate: 
    INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Introduction to Quarkus', true, 0, null)
Hibernate: 
    INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Hibernate with Panache', false, 1, null)
Hibernate: 
    INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Visit Quarkus web site', false, 2, 'https://quarkus.io')
Hibernate: 
    INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Star Quarkus project', false, 3, 'https://github.com/quarkusio/quarkus/')
2020-09-22 12:44:26,705 INFO  [io.quarkus] (main) Quarkus 0.15.0 started in 3.181s. Listening on: http://0.0.0.0:8087
2020-09-22 12:44:26,705 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-validator, jdbc-h2, narayana-jta, resteasy, resteasy-jsonb]
```
In the browser, I get the error message `Can't connect to http://0.0.0.0:8087`

**Comment by cescoffier** [comment]
Try with http://localhost:8087

Le mar. 22 sept. 2020 à 14:52, FrankBergemann <notifications@github.com> a
écrit :

**Comment by FrankBergemann** [comment]
Hi Clement, 
Setting `quarkus.http.port=portnumber` in application properties as you advised is working fine. I made the mistake forgetting to expose the `portnumber` to the host when running Quarkus todo within a docker container. All okay once this is done.
Ticket closed.
Kind regards
-- Frank
