### ISSUE TITLE
CircleCI: add support for native application

### ISSUE THREAD

**Issue by jmini** [cescoffier/quarkus-todo-app#8]
See the blog post [Using CircleCI to Build a Native Quarkus Application](https://quarkus.io/blog/quarkus-app-circleci-build/).

I think it can be applied to this example project as well.

**Comment by cescoffier** [comment]
it would be great!

**Comment by cescoffier** [comment]
I switched to Github actions to get that working - as it was more than required (it caught a lot of issues with the native tests)
